# included templates
include:
  - local: '.gitlab-ci-trigger.yml'
  - 'https://gitlab.com/senbox-org/snap-engine/raw/master/.gitlab-ci.yml'

mvn-build:
  artifacts:
    paths:
      - "${MAVEN_PROJECT_DIR}/**/target/*.jar"
      - "${MAVEN_PROJECT_DIR}/**/target/classes"
      - "${MAVEN_PROJECT_DIR}/**/target/*.nbm"
      - "${MAVEN_PROJECT_DIR}/**/target/site"
      - "${MAVEN_PROJECT_DIR}/**/target/surefire-reports"
  needs:
    - job: compile-snap-engine