# included templates
include:
  - 'https://gitlab.com/senbox-org/snap-engine/raw/13.x/.gitlab-ci.yml'

mvn-build:
  artifacts:
    paths:
      - "${MAVEN_PROJECT_DIR}/**/target/*.jar"
      - "${MAVEN_PROJECT_DIR}/**/target/classes"
      - "${MAVEN_PROJECT_DIR}/**/target/nbm/*.nbm"
      - "${MAVEN_PROJECT_DIR}/esasnappy-kit/target/*.jar"
      - "${MAVEN_PROJECT_DIR}/esasnappy-kit/target/classes"
      - "${MAVEN_PROJECT_DIR}/esasnappy-kit/target/nbm/*.nbm"
      - "${MAVEN_PROJECT_DIR}/esasnappy-kit/target/nbm/clusters/extra"
      